### ISSUE TITLE
Test and decide naming convention and implementation of Mixins

### ISSUE THREAD

**Issue by gregorpirgie** [acdh-oeaw/apis-core-rdf#516] opened 2023-12-20 12:04 UTC
## Background: 

Mixins are one way to encapsulate functionality that can than be added to other classes. The other approach is using abstract base classes or non abstract classes to inherit from. All three approaches work via inheritance. 

## 1. Naming convention

- there is a convention that  one of the differences between mixins and classes is, that a class doesn't work if it only inherits from a mixin. Like so (using a View as an example: 

```python 
# note that this mixin does not inherit from django's build in View-class.
class MyViewMixin: 

    def mixin_method(self):
        pass

# this should not work according to the above convention (and it would not work as a view in django in this case)
class MyView(MyMixin):
    pass

# but this should work 
class MyView(MyMixin, View):
    pass
```

Question here is: Do we want to adhere to this convention? Or do we need to diverge from it and communicate it in the dev-documentation?
- the convention would be that if a class provides functionality that should be inherited but can be used via single inheritance, it should be not named a "mixin" but like the type of class that it extends (examples are TableView vs. TableMixin, etc.)
- the other convention to take into consideration is that mixins should only inherit form other mixins, but not other classes. 

## 2. Check compatability of our mixin implementation 

- If we use mixins that inherit from standalone classes, we need to check that all mixins that might be used on the same type of class are compatible with each other. The most common problem that might occur is an unexpected or unresolvable MRO (Method Resolution Order). For example: 

```python 

class MyMixinA(View):
    
    # overrides save method of view
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class MyMixinB(View):
    
    # also overrides save method of view
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

# this might break in certain conditions, which we should test. 
# This class now inherits the build-in View class three times
class MyView(MixinA, MixinB, View):
     pass
```

- We would need to test that all mixins we write for a certain type of class (like View, Table, Form, Model) are compatible with each other (i.e. can be used in the same class). It should also not matter in which order you add a mixin to the inheritance tree – as long as the django provided class comes last in the inheritance tree. 
- Usually python throws an error if the MRO can't be resolved, but we should test also if the functionality provided by each mixin still works as expected, even if the MRO does not break. 

For reference on Mixin impemenations in Django see: 
- [Classy Class Based Views](https://ccbv.co.uk/projects/Django/5.0/)
- specific example on the difference between a implementing form functionality within a View and within a Mixin: 
  - [FormMixin](https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/FormMixin/)
  - [FormView](https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/FormView/)

**Comment by gregorpirgie** [comment] 2023-12-20 12:09
Regarding the topic of compatability of mixins, django itself warns that not all django provided mixins work together: 
- [django docs](https://docs.djangoproject.com/en/5.0/topics/class-based-views/mixins/#using-django-s-class-based-view-mixins)

But we should still test that those mixins that we want to be allowed to be used together actually work.

**Comment by koeaw** [comment] 2023-12-20 15:09
Ahh, thanks, @gregorpirgie, now I finally know (again) why I was confused about the broader use of the term "mixin" during previous discussions. In my mind it wasn't just _any_ class that other classes inherit from (but I couldn't remember what differentiated it).

**Comment by b1rger** [comment] 2024-09-06 08:58
Closing this. We discussed the issue at length, but the issue is not actionable. For the `GenericModel` we use the `abc` (abstract base class) namespace, so its clear that this is not a mixin

**Closed by b1rger** 2024-09-06 08:58 UTC
Labels: documentation, refactor, feature-request, needs-design-decision
