### ISSUE TITLE
Duplicate button/action results in error(s) 

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#889] opened 2024-06-04 11:13 UTC
I may not have tried out duplicating before, so not sure if these errors are new, but I'm experiencing them on the latest version, `v0.19.0`.

I'm seeing 3 variations so far, which I'm interpreting to be based on:
1. source object having relations attached to it,
2. source object having field(s) with unique constraint,
3. nothing in particular (regular ole source object with a unique, incremental id).

Example for 1):

```
Exception at /apis/entities/entity/person/18770/duplicate/

subj, obj, or prop is None

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/apis/entities/entity/person/18770/duplicate/
Django Version: 	4.2.13
Exception Type: 	Exception
Exception Value: 	

subj, obj, or prop is None

Exception Location: 	/PATH/TO/VENV/lib/python3.11/site-packages/apis_core/apis_relations/models.py, line 293, in save
Raised during: 	apis_core.apis_entities.views.EntitiesDuplicate
Python Executable: 	/PATH/TO/VENV/bin/python
Python Version: 	3.11.9
```

Example for 2):

```
IntegrityError at /apis/entities/entity/work/10342/duplicate/

duplicate key value violates unique constraint "apis_ontology_work_siglum_6f5a6fe2_uniq"
DETAIL:  Key (siglum)=(AEZ) already exists.

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/apis/entities/entity/work/10342/duplicate/
Django Version: 	4.2.13
Exception Type: 	IntegrityError
Exception Value: 	

duplicate key value violates unique constraint "apis_ontology_work_siglum_6f5a6fe2_uniq"
DETAIL:  Key (siglum)=(AEZ) already exists.

Exception Location: 	/PATH/TO/VENV/lib/python3.11/site-packages/psycopg/cursor.py, line 732, in execute
Raised during: 	apis_core.apis_entities.views.EntitiesDuplicate
Python Executable: 	/PATH/TO/VENV/bin/python
Python Version: 	3.11.9
```

Example for 3):

```
AttributeError at /apis/entities/entity/researchperspective/19312/duplicate/

'NoneType' object has no attribute 'id'

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/apis/entities/entity/researchperspective/19312/duplicate/
Django Version: 	4.2.13
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'id'

Exception Location: 	/PATH/TO/VENV/lib/python3.11/site-packages/apis_core/apis_entities/views.py, line 30, in get
Raised during: 	apis_core.apis_entities.views.EntitiesDuplicate
Python Executable: 	/PATH/TO/VENV/bin/python
Python Version: 	3.11.9
```

**Comment by b1rger** [comment] 2024-06-04 11:21
I just tried 1) and 3) and could not reproduce the problem

**Comment by koeaw** [comment] 2024-06-04 11:31
Interesting, I just noticed that objects actually seem to get duplicated either way...

**Comment by b1rger** [comment] 2024-06-04 11:49
2) make sense, because the `duplicate` method only pops the `id`:
https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_metainfo/models.py#L51

this should probably be fixed to remove all values that are expected to be unique from the new object

no relation in case of 1) makes sense because you received an exception when the relation was created, but without more information about where the error originated its hard to say why

**Comment by koeaw** [comment] 2024-06-04 11:59
So with 3), the error is caused by [this statement](https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_relations/models.py#L292-L293).

A cursory look suggests that either `self.subj`  or `self.obj` are missing (on `TempTriple`), hence the target object doesn't end up with any relations. Curiously though, _the source object_ has its relations duplicated... Huh.

**Comment by b1rger** [comment] 2024-06-04 12:05
> So with 1), the error is caused by [this statement](https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_relations/models.py#L292-L293).
> 
> A cursory look suggests that either `self.subj` or `self.obj` is missing (on `TempTriple`), hence the target object doesn't end up with any relations. Curiously though, _the source object_ has its relations duplicated... Huh.

The copying happens in this signal receiver:
https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_relations/signals.py#L12

based on your description, the relation is duplicated (Line 16 or 20), but apprently the `duplicate` is not set correctly. Does the log statement show the correct duplicate?

**Comment by koeaw** [comment] 2024-06-04 14:32
Replacing `duplicate` with `newobj` [at the end](https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_metainfo/models.py#L73-L75) of the `duplicate` method of `apis_metainfo/models.py` seems to fix things for me. At least for case 1).

The error goes away, I'm being redirected to the edit view of the new, duplicate object (side note: a visual indicator would help with differentiation), and the new object looks identical to the old one, incl. relations.

**Comment by koeaw** [comment] 2024-06-04 14:36
(The error in case 3) may actually have been part of case 1) as well, further up the chain; will need to check.)

**Comment by b1rger** [comment] 2024-06-04 14:45
> side note: a visual indicator would help with differentiation

[Click me!](https://github.com/acdh-oeaw/apis-core-rdf/issues/new?title=Add%20visual%20indicator%20for%20duplicate%20view)

**Comment by koeaw** [comment] 2024-06-04 14:47
> > side note: a visual indicator would help with differentiation
> 
> [Click me!](https://github.com/acdh-oeaw/apis-core-rdf/issues/new?title=Add%20visual%20indicator%20for%20duplicate%20view)

Yeeees, I was going to open a new issue for that!

**Comment by b1rger** [comment] 2024-06-04 14:51
> Ehh, I just (_re!_)discovered that the duplicate and edit buttons in my list view don't link to the generic URL format (views). Might it be related to that? (Example: `/apis/entities/entity/person/18770/duplicate/`)

there is no generic url format for the duplicate view, because the duplicate method is not part of generic models, but only of entities. So its only routed in `apis_entities.urls`:
https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_entities/urls.py#L72

Please be also aware of 08f690435822074d373407f62fef9941703b3c5c (which was merged *after* v0.19.0)

**Comment by koeaw** [comment] 2024-06-04 16:44
> this should probably be fixed to remove all values that are expected to be unique from the new object

So I've just found something else that I guess we actually don't want to have duplicated in our project... which is a `ForeignKey` to a model which we use to document where data came from.

There currently is no way to exclude certain data from being duplicated, e.g. right in the model, is there? Could there be?

**Comment by b1rger** [comment] 2024-06-04 16:48
> > this should probably be fixed to remove all values that are expected to be unique from the new object
> 
> So I've just found something else that I guess we actually don't want to have duplicated in our project... which is a `ForeignKey` to a model which we use to document where data came from.
> 
> There currently is no way to exclude certain data from being duplicated, e.g. right in the model, is there? Could there be?

You can override the `duplicate` method or trigger the removal of the foreign key using the `post_duplicate` signal

**Comment by koeaw** [comment] 2024-06-04 17:11
> You can override the `duplicate` method or trigger the removal of the foreign key using the `post_duplicate` signal

Thanks!

So, would signals also be the way to deal with `unique` fields on a case-by-case (model-by-model) basis where that would make sense? Rather than blanket removing all `unique` fields.

I'm assuming this would be the only way to prevent duplication failing altogether in cases where a `unique` field is not allowed to simultaneously be `null`? (Object creation won't happen if no value is provided for the field?)

**Comment by b1rger** [comment] 2024-06-05 07:07
> > You can override the `duplicate` method or trigger the removal of the foreign key using the `post_duplicate` signal
> 
> Thanks!
> 
> So, would signals also be the way to deal with `unique` fields on a case-by-case (model-by-model) basis where that would make sense? Rather than blanket removing all `unique` fields.

I'm not sure if thats not something we should implement in APIS directly - duplicating the value of fields that are set to be unique does not really make any sense anyway, so we should probably find a way to exclude all those fields from duplication.

**Comment by koeaw** [comment] 2024-06-05 08:14
Hmm, but what if we don't want to lose those fields? Would there be a way to signal "please don't remove this"?

What I did for now to deal with the `unique` field on my end is [this](https://github.com/acdh-oeaw/apis-instance-frischmuth/blob/a26fed799012738a440c7734b5a35f14bf8dc99f/apis_ontology/signals.py#L12).

Relatedly, the way the duplicates are created does not take into account any individual `save` functions, does it? I was thinking their may be special cases of fields for which 1:1 duplication of values doesn't make sense, e.g. fields that are meant to reflect object creation time or similar.

**Comment by b1rger** [comment] 2024-06-05 08:18
> Hmm, but what if we don't want to lose those fields? Would there be a way to signal "please don't remove this"?

I don't understand - either its unique or its not. What should happen with the value of the field? It cannot be stored in the database a second time


> Relatedly, the way the duplicates are created does not take into account any individual `save` functions, does it? 

It does call `save()`:
https://github.com/acdh-oeaw/apis-core-rdf/blob/08f690435822074d373407f62fef9941703b3c5c/apis_core/apis_metainfo/models.py#L73

**Closed** 2024-06-05 09:53 UTC
Labels: bug
