### ISSUE TITLE
history: make the `version_tag` in the history module more flexible

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#796] opened 2024-04-19 06:42 UTC
currently the `version_tag` is a `charfield` and filtering for corresponding  relations is thus a bit cumbersome.
Either reuse the tagging library to tag the version, or create a dedicated model in history module

**Comment by b1rger** [comment] 2024-11-13 15:58
closing as duplicate of #785 and #1117

**Closed by b1rger** 2024-11-13 15:58 UTC
