### ISSUE TITLE
Check for legacy code if it's still needed

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#89] opened 2023-03-10 15:15 UTC
Throughout the codebase there is plenty of legacy code with unclear purpose. 

We need to check these parts and remove or replace them.

Currently some are taged like this (of course not exhaustively):
```
# TODO RDF: Check if this should be removed or adapted
```

This `TODO` should be reused whenever you come across a code segment you're not sure about, so that we can collect them under this tag. 

Now there are 10 such occurrences in https://github.com/acdh-oeaw/apis-core-rdf/commit/10548ec60e14db147168481ee1f30ee1fed0c018

**Comment by koeaw** [comment] 2023-04-12 11:36
Closing this as duplicate of the linked ticket, but (anyone) feel free to reopen it if you disagree with [my reasoning](https://github.com/acdh-oeaw/apis-core-rdf/issues/110#issuecomment-1505111207) over there.

**Comment by steffres** [comment] 2023-04-25 12:01
This issue is the more appropriate one compared to the other issue, as here are some code markers provided already.

**Comment by sennierer** [comment] 2024-03-20 08:49
closing as to generic

**Closed by sennierer** 2024-03-20 08:49 UTC
