### ISSUE TITLE
Give correct plural name for classes in apis_core models

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#18] opened 2022-10-20 06:38 UTC
Adding a "verbose_name_plural" attribute to the meta class like this should tell Django to not use the default plural form, for example -  "Propertys"
```
class Property(RootObject):
    class Meta:
        verbose_name_plural = "Properties"

```

**Comment by koeaw** [comment] 2022-10-25 10:51
I tried to fix this already in one or two places, but recently realised that we're missing an additional `context` attribute to differentiate between singular and plural names. The _same attribute_ `context["class_name"]` is used e.g. for "Browse ENTITY" and "Create new ENTITY" in an entity's list view:

<image src="https://user-images.githubusercontent.com/113020169/197750259-1b4dd2a1-9790-41b7-9947-5c0643bd10e8.png" width="300">

So my changes did not fully fix this, they just switched out the singular verbose name for the plural verbose name, see [the bottom-most changes in this views.py file](https://github.com/acdh-oeaw/apis-core-rdf/commit/67059c6853524f0fe2ae96104b64c339dc8895fc).

Semi-relatedly, in lots of other places, we default to using the lowercase (slug) class name, which then gets `title()`'d (!) _instead of_ using a) the _actual_ class name to reference model classes and b) verbose names to output human-readable names. Which in the case of my project has led to all sorts of problems already because I follow Python/Django convention and camel-case class names. I've fixed this particular problem in more places already, though I'm sure searching for `.title()` will come up with more instances of `entity.title()` and similar where the problem is not yet fixed. (I currently have an open issue for one of these in relation to `entity_settings` over on GitLab, and it looks to me like one of the culprits is in fact right there in the snippet of the views.py file I linked above!)

I believe I began reworking the `context["class_name"]` again, because I saw it's being used in template tags that relate to PR acdh-oeaw/apis-rdf-devops#5 (currently on hold), I'll see if there's any useful stuff I can put in a branch for you to potentially include.

**Comment by koeaw** [comment] 2022-10-25 11:06
Another problem we have, which a good bunch of my changes so far did not address or take into account (out of not knowing better), is that there's a lack of consistency or clarity in e.g. variable names for referring to classes or class attributes.

There are lots of `entity` (sometimes `ent` or `ent_...`) variables which are primarily used to store class names, though it's rarely made clear which name is being referred to – actual name vs. slug vs. verbose name. To me it seems that strings needed for e.g. creating various links were simply reused for all sorts of outputs to users on the frontend... hence all the title-casing on those variables.

**Comment by koeaw** [comment] 2022-10-25 18:02
Ohh, I may have (slightly) misunderstood what you were trying to say – I primarily wanted to resolve this for my project's entity classes. didn't really look at any of the classes they inherit from – but it's made me aware of a flaw in my fixes.

**Comment by koeaw** [comment] 2022-10-31 14:23
I pushed [a branch](https://github.com/acdh-oeaw/apis-core-rdf/tree/kk/fix/entity_references_listview) with my attempt to fix this last week (just force pushed again after splitting one commit in two and adding another). It might actually make sense to turn it into a PR as-is.

**Comment by koeaw** [comment] 2022-12-19 09:27
Closing this (and moving to Done) because the PR which resolved this already got merged.

(Heads-up, @gythaogg: linking issues from the "Development" section of a PR (menu on right-hand side) and moving them to the Done column in Projects will auto-close them on merge!)

**Closed by koeaw** 2022-12-19 09:27 UTC
Labels: app-entities
